name: Continuous Integration API

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch ${{ github.event.inputs.branch_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Check styles
        run: |
          ./bin/php-cs-fixer-v3.phar fix src --dry-run --verbose --diff
          ./bin/php-cs-fixer-v3.phar fix tests --dry-run --verbose --diff

  unit:
    runs-on: ubuntu-22.04
    steps:
      -   name: Setup PHP with PECL extension
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run composer
        run: make composer/install

      - name: Run tests
        run: make phpunit/all
